### ISSUE TITLE
Agenda - InnerSource SIG Leadership Meeting - Wednesday 3 February 2021

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#1]
## Date
Wednesday 3 February 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- Aaron Searle, Morgan Stanley
- Anthony Vacca, RBC
- Arthur Maltson, Capital One
- Clare Dillon, ISC
- Danese Cooper, President ISC
- Daniela Zheleva, Deutsche Bank

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### SIG Operations
- Discussion about how other SIGs work. Example, the Cloud Readiness meets every 2 weeks, have a Kanban board and actual tasks through there.
  - This is part of the formal process is to setup the mailing list, setup the repo, allow people to join.
  - A number people already expressed interest, we may reach out to them after.
  - Went a bit slowly as people were hesitant to provide code.
- How does this relate to the InnerSource Commons group?
  - InnerSource Commons is upstream, so the FINOS SIG is safer space for FinTech companies where they've already signed NDAs, etc.
  - Any patterns should be considered for transfer to InnerSource Commons.
  - Working group towards FinTech participation in the larger InnerSource Commons.
  - Good example, the Marketplace from Deutsche Bank. Let's say that Deutsche Bank wants to Open Source it, this SIG will work to help make sure that project is usable for everyone, not just the banking industry.
  - Another goal of the Commons was to help larger institutions get credit for what they're working on vs. the semi-old school way of being quiet about their con
  - FINOS will not squat on the trademark of InnerSource Commons and once the trademark is made, FINOS will license it.
- How do we prefer to communicate between each other?
  - Since Slack is not accessible for everyone, FINOS in general recommends something more open.
  - @mcleo-d also suggested the new GitHub Discussions, might consider it.
  - For now will follow the standard FINOS practice.
- Logo discussion will kick off on the mailing list.
- Suggestion that the first few meetings are more around discovery of where different people are at in terms of InnerSource and getting on the same page.
  - Perhaps make the first meeting longer?
  - Maybe have a rolling "share your experience" slot in each meeting.
  - Maybe start small, understand each of our areas and what we want to achieve.
  - Key outcome from sharing could be what do we want to achieve. How do we standardize starting in InnerSource for FINOS organizations and the broader group.
  - Structure: 10 minute presentation, 10 minutes of chat and questions per person. 30 minutes round table. So 2.5 hours with the end of what we want to achieve.
- Already booked March 3rd to have another Open Source readiness event.
- Meeting timing: morning for the EST folks and evening for the GMT folks.
- February 17th for 2.5 hours from 8:30am to 11am. Just the 6 of us with the aim to agree initial themes for the SIG to explore. Meetings can subsequently be opened to the wider interested audience.

### Open Source Readiness March 3rd Meeting
- If we wanted, we could follow the same format as the previous meeting where the first 30 minutes was 2 presentations: someone shares their InnerSource work or experience and an industry (?) update, then 30 minute panel/Q&A.
- A number of the leadership team has already given a presentation, call for participants.
- Discussed @amaltson and Roderick's talk, agreed this talk would have some interested parties at the Open Source Readiness meetup.
- This would mean the format would be a 30 minute presentation and then 30 minutes of discussion.
- Question arose whether we could play an existing recording of the talk.
- It'd be possible to do it live, but @amaltson needs to check with Roderick about his availability and willingness to do it live.
- Technical hurdle to doing it live, WebEx doesn't work with @amaltson's DSLR as webcam setup, even though [Canon claims to work with WebEx](https://www.usa.canon.com/internet/portal/us/home/support/self-help-center/eos-webcam-utility).
  - @amaltson could in theory present off the laptop camera, just needs to reconfigure desk.
- Definite preference on the pre-recorded talk if possible.

### Logistical Steps to Get SIG Set Up
- finos/community#84 checklist covers most of the setup.
- Project communication channel is outstanding, will make a mailing list at least for invites.
- Repository transfer, question of whether the InnerSource Commons patterns repo has been forked yet.
- Need to work with FINOS marketing around announcements and press releases. FINOS team will help posting it on social media, etc.
- Onboarding training is something we all have to do.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Provide @mcleo-d the GitHub profiles of the InnerSource SIG Leadership in the comments of this issue to add to the SIG maintainers group on GitHub.
- [ ] Provide @mcleo-d the InnerSource SIG repository description which will also be used on https://landscape.finos.org/ 
  - See https://github.com/finos/innersource screenshot below
![Screenshot 2021-02-03 at 11 49 03](https://user-images.githubusercontent.com/6029572/106743113-d80cdc80-6615-11eb-8e1b-179dd0c367a2.png)
- [ ] AOB, Q&A & Adjourn (5mins)
- [ ] Goals and operation of what we want to achieve as part of this SIG.
- [ ] Plan out participation in the Open Source Readiness group, which will meet about this SIG every 2 months.
- [ ] Number of standard logistical steps to go through per @mcleo-d.

## Decisions Made
- [ ] Arthur and Roderick will present at March 3rd Open Source Readiness session.
- [ ] @anvacca volunteered to present at the Open Source Readiness meeting in May or the one after.
- [ ] @anvacca will facilitate the 2.5 hour February 17th meeting.

## Action Items
- [ ] @claredillon to add the About section to the repo.
- [ ] @claredillon working with @mcleo-d to figure out which communication platform options we have and will bring it back to the group.
- [ ] @claredillon will book the upcoming February 17th meeting - _@mcleo-d response https://github.com/finos/InnerSource/issues/1#issuecomment-773258770_
- [ ] @claredillon will check with William what his requirements are for podcasts.
- [ ] @claredillon will confirm about the move to Zoom and if it's happening - _@mcleo-d response https://github.com/finos/InnerSource/issues/1#issuecomment-773254884_
- [x] @amaltson to share link to presentation slides.
- [ ] @amaltson to check with Roderick about doing a live talk.
- [ ] @claredillon to get more details about the training from @mcleo-d 
- [x] @claredillon will confirm @mcleo-d already has all the contributor metadata - _@mcleo-d response https://github.com/finos/InnerSource/issues/1#issuecomment-773249212_

### WebEx info
- Meeting link: 
- Meeting number: 
- Password:
- Call-in:

**Comment by mcleo-d** [comment]
@claredillon and @danese - This GitHub Issue has been raised to represent your first InnerSource SIG leadership meeting. Please  note I have added the following points below ...

```
- Provide @mcleo-d the GitHub profiles of the InnerSource SIG Leadership in the comments of this issue to add to the SIG maintainers group on GitHub.
- Provide @mcleo-d the InnerSource SIG repository description which will also be used on https://landscape.finos.org/
```

**Comment by daniela-g-zheleva-db** [comment]
hello 🎉

**Comment by amaltson** [comment]
Hello 👋

**Comment by claredillon** [comment]
Hi there!

**Comment by aaronsearle** [comment]
Here

**Comment by claredillon** [comment]
Anthony Vacca is also attending this meeting

**Comment by claredillon** [comment]
Danese Cooper also in attendance

**Comment by anvacca** [comment]
Hello!

**Comment by amaltson** [comment]
Here's the slides for Roderick and I's ["From One API Deployment to Thousands, The Journey of an InnerSource CI/CD Framework" talk](https://speakerdeck.com/amaltson/cd-framework). I'll update it in the very near future to include the speaker notes embedded in the slides.

**Comment by mcleo-d** [comment]
Hi all - It's great to see you all had a constructive first meeting. 

Thank you for owning the repo and using the issues 😀  

James.

**Comment by mcleo-d** [comment]
@claredillon,

I can confirm I have the metadata and the request is now done. I have marked the following item as complete on your behalf.

> @claredillon will confirm @mcleo-d already has all the contributor metadata.

**Comment by mcleo-d** [comment]
Hi @claredillon,

Regarding the following item ...

> @claredillon will confirm about the move to Zoom and if it's happening.

Zoom is currently being worked through with the LF as webex allows us to schedule reoccurring project and SIG meetings in advance and add them to the [FINOS Project Calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York), whereas Zoom is allocated to individuals and isn't centralised right now.

We'll keep you posted as Zoom comes online for projects and SIGs. 

Feel free to mark the item as complete if I covered all points correctly.

James.

**Comment by mcleo-d** [comment]
@claredillon,

Lets have a chat about the following item as it'll be good for the team to raise an [InnerSource SIG Meeting Agenda and Minutes](https://github.com/finos/InnerSource/issues/new/choose) issue so I can organise the webex and add to the [FINOS Project Calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York) if this is the first official SIG meeting?

> @claredillon will book the upcoming February 17th meeting

Cheers, 

James.

**Comment by mcleo-d** [comment]
@claredillon - I've scheduled a meeting for Friday 5th February at 10am UK where we can go through the rest of the items that need a little more detailed discussion 😺

**Comment by amaltson** [comment]
Hello @mcleo-d 

> Zoom is currently being worked through with the LF as webex allows us to schedule reoccurring project and SIG meetings in advance and add them to the [FINOS Project Calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York), whereas Zoom is allocated to individuals and isn't centralised right now.
> 
> We'll keep you posted as Zoom comes online for projects and SIGs.

The origin of this ask came from a discussion of how we could handle Roderick and I's presentation at the Open Source Readiness meeting. I've updated the meeting notes to reflect as such. Basically it comes down to my setup and WebEx not supporting it, it's not a big deal though.

**Comment by mcleo-d** [comment]
Thanks @amaltson - I'm more than happy to work though some WebEx scenarios in advance that'll enable you to present. For instance, I'm more than happy to tag team and share the presentation whilst you and Roderick present.

I'll also investigate where we are with Zoom and whether it can be used for single meeting scenarios to cover this type of issue.

James.

**Comment by mcleo-d** [comment]
Hi Team - Just letting you know I have closed this issue as the `close` event kicks off our meeting registration action in FINOS. Please feel free to keep commenting.

**Comment by amaltson** [comment]
@mcleo-d I realized why WebEx isn't working, I have an older version of the software installed because of a compatibility issue with Screenflow. I'll get the newer version installed for the meeting. However, would it be possible to share the video recording of our talk rather than Roderick and I doing it live? Roderick's preference would be to have the video play, what do you think? /cc @claredillon
